@server = localhost:8080/admin

### Test
GET {{server}}

### getNumberOfPosts
# @name getNumberOfPosts
GET http://{{server}}/count

### getNumberOfAllUsers
# @name getNumberOfUsers
GET http://{{server}}/count/all

### getNumberOfUsers
# @name getNumberOfPosts
@nationality = china
GET http://{{server}}/count/{{nationality}}

###