@server = localhost:8080/admin

### Test
GET {{server}}

### getNumberOfPosts
# @name getNumberOfPosts
GET http://{{server}}/count/posts

### getNumberOfAllUsers
# @name getNumberOfUsers
GET http://{{server}}/count/allUsers

### getNumberOfUsers
# @name getNumberOfPosts
@nationality = china
GET http://{{server}}/count/{{nationality}}

###