@server = http://localhost:8080/auth

### Test
GET {{server}}

### Login
POST {{server}}/login
Content-Type: application/json

{
  "socialId" : "1",
  "secret" : "myM32FAihR1lCrCOtX3KGHo96Z7hsjHw",
  "provider" : "kakao"
}
