@server = 192.168.0.183:8080/user

### Test
GET {{server}}

### Create User
# @name createUser
# authority 나중에 빠져야함.
POST http://{{server}}
Content-Type: application/json

{
  "loginRequestDTO": {
    "socialId": "1234",
    "secret": "myM32FAihR1lCrCOtX3KGHo96Z7hsjHw",
    "provider": "kakao"
  },
  "userRequestDTO": {
    "email": "email_example",
    "name": "name_example",
    "nickname": "nickname_example",
    "nationality": "nationality_example",
    "language": "language_example",
    "profileImage": "profileImage_example",
    "introduction": "introduction_example",
    "city": "city_example",
    "authority" : "User",
    "gender": "남자",
    "mbti": "mbti_example",
    "interests": "interests_example",
    "birthday": "2024-12-21"
  }
}

###

### Get User by ID
# @name getUser
@userId = acaa8338-ecc4-4fba-8c57-f6ed7f114646
GET http://{{server}}/{{userId}}
###

### Find All Users
# @name findAllUsers
GET http://{{server}}/
###

### Update User
# @name updateUser
PUT http://{{server}}/{{userId}}
Content-Type: application/json
{
  "UserRequestDTO_key_1": "updated_value_1",
  "UserRequestDTO_key_2": "updated_value_2"
}

###

### Delete User
# @name deleteUser
DELETE http://{{server}}/{{userId}}